from typing import Iterable

import psycopg


CURRENT_LIST_ID_KEY = "current_list_id"


class ShoppingStore:
    def __init__(self, database_url: str):
        self.database_url = database_url
        self._initialize()

    def _connect(self):
        return psycopg.connect(self.database_url)

    def _initialize(self):
        with self._connect() as connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS shopping_items (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    list_id INTEGER NOT NULL,
                    content TEXT NOT NULL,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS shopping_state (
                    key TEXT PRIMARY KEY,
                    value INTEGER NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_shopping_items_list_id_id
                ON shopping_items (list_id, id)
                """
            )
            self._get_current_list_id(connection)

    def _get_max_list_id(self, connection) -> int | None:
        row = connection.execute("SELECT MAX(list_id) FROM shopping_items").fetchone()
        if row is None or row[0] is None:
            return None
        return int(row[0])

    def _get_current_list_id(self, connection) -> int:
        row = connection.execute(
            "SELECT value FROM shopping_state WHERE key = %s",
            (CURRENT_LIST_ID_KEY,),
        ).fetchone()

        if row is not None:
            return int(row[0])

        list_id = self._get_max_list_id(connection) or 1
        connection.execute(
            "INSERT INTO shopping_state (key, value) VALUES (%s, %s)",
            (CURRENT_LIST_ID_KEY, list_id),
        )
        return list_id

    def _list_items(self, connection, list_id: int) -> list[str]:
        rows = connection.execute(
            """
            SELECT content
            FROM shopping_items
            WHERE list_id = ?
            ORDER BY id
            """,
            (list_id,),
        ).fetchall()
        return [row[0] for row in rows]

    def add_items(self, items: Iterable[str]) -> int:
        cleaned_items = [item.strip() for item in items if item and item.strip()]

        with self._connect() as connection:
            list_id = self._get_current_list_id(connection)
            if cleaned_items:
                connection.executemany(
                    "INSERT INTO shopping_items (list_id, content) VALUES (?, ?)",
                    [(list_id, item) for item in cleaned_items],
                )
            return list_id

    def get_current_list_id(self) -> int:
        with self._connect() as connection:
            return self._get_current_list_id(connection)

    def get_current_list(self) -> tuple[int, list[str]]:
        with self._connect() as connection:
            list_id = self._get_current_list_id(connection)
            return list_id, self._list_items(connection, list_id)

    def list_current_items(self) -> list[str]:
        return self.get_current_list()[1]

    def get_status(self) -> dict[str, int | str]:
        with self._connect() as connection:
            list_id = self._get_current_list_id(connection)
            current_item_count = connection.execute(
                "SELECT COUNT(*) FROM shopping_items WHERE list_id = %s",
                (list_id,),
            ).fetchone()[0]
            max_list_id = self._get_max_list_id(connection) or 0
            return {
                "db_path": str(self.db_path),
                "current_list_id": list_id,
                "current_item_count": int(current_item_count),
                "max_list_id": max_list_id,
            }

    def advance_list(self) -> int:
        with self._connect() as connection:
            list_id = self._get_current_list_id(connection) + 1
            connection.execute(
                "UPDATE shopping_state SET value = ? WHERE key = ?",
                (list_id, CURRENT_LIST_ID_KEY),
            )
            return list_id
